Unverify (and new popie fix)
pumpkin-py/pumpkin-management pull request #22
Opened 2021-11-09 13:17 UTC by Czechbol

Resolves #7

2021-11-09 18:52 UTC, sinus-x requested changes
I can feel the effort that was poured into this. The logic seems fine, at least I haven't found any problems.

2021-11-09 18:52 UTC, sinus-x commented on unverify/database.py
> +    def get(guild_id) -> GuildConfig:
This type hint should be `Optional[GuildConfig]`

2021-11-09 18:52 UTC, sinus-x commented on unverify/database.py
> +        - :class:`sqlalchemy.orm.exc.MultipleResultsFound`: Multiple items were found (which is not expected).
Why is there a `-`, if all other lists can be defined by indentation? Is it necessary?

2021-11-09 18:52 UTC, sinus-x commented on unverify/database.py
> +                guild_id=member.guild.id,
Since we're raising an exception, we don't have to use `else` statement, as the execution would be stopped by then.

2021-11-09 18:52 UTC, sinus-x commented on unverify/database.py
> +        :class:`UnverifyItem`: The removed item.
Shouldn't this be indented?

2021-11-09 18:52 UTC, sinus-x commented on unverify/database.py
> +            raise ValueError
There are `ValueError` raised a lot, maybe they should have some content describing what is wrong? I can be convinced otherwise. In my modules, I've been using `return None` instead of raising exceptions, I wonder what is "prettier" solution.

2021-11-09 18:52 UTC, sinus-x commented on unverify/database.py
> +        return result
SInce the object gets deleted, `None` would get returned instead (correct me if I'm wrong). If you want to return the object, use `.dump()` to return its `Dict` representation.

2021-11-09 18:52 UTC, sinus-x commented on unverify/database.py
> +        :class:`Optional[UnverifyItem]`
Again, the indentation. I won't be commenting on further occurences.

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +from discord import Guild, Member
Why not just use `discord.Guild`?

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +from discord.ext import tasks, commands
Generally, using
```py
import discord
from discord.ext import commands
```
is usually enough. I feel like doing more is excessive. But it's just a note, not requirement. It's your module.

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +                    f"Reverify failed: Guild ({item.guild_id}) was not found. Setting status to `guild could not be found`",
Splitting this line may be a good idea.

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +                        ),
We're not translating logs, they are all in English. Should we start doing that? Is it worth the translation effort?

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +                        f"Returning role {role.name} to {member.name} ({member.id}) failed. Insufficient permissions.",
Why is it twice here? The first one can go away.

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +    ) -> tuple[list[int], list[int]]:
`tuple`, `list` do not work in Python 3.8, please use their `typing.Tuple`, `typing.List` alternatives.

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +        with contextlib.suppress(discord.Forbidden):
Can this be moved just below where the member is contacted? It would get a bit easier to read if the suppress was directly above the line that may cause the exception.

2021-11-09 18:52 UTC, sinus-x commented on unverify/module.py
> +            await ctx.reply(_(ctx, "Is this member really unverified?"))
:)

We know if the member is unverified or not, I don't think we should be asking these kinds of questions.

2021-11-09 20:30 UTC, ArcasCZ commented on unverify/database.py
> +            raise ValueError
I think returning None would be better way since you can just easily ignored that return value (or fact, that you tried to delete non-existing item) if you wish so and you don't have to catch it and pass.

2021-11-09 20:34 UTC, ArcasCZ commented on unverify/database.py
> +        return result
I think there was way to return number of affected rows. That would also handle that ValueError raising since you could just do delete and then return number of affected rows and check it.

```Python
    def remove(guild_id: int, channel_id: int):
        query = (
            session.query(HashChannel)
            .filter_by(guild_id=guild_id, channel_id=channel_id)
            .delete()
        )
        session.commit()
        return query
```
This is example from dhash.

2021-11-09 20:36 UTC, ArcasCZ commented on unverify/module.py
> +                        ),
I don't think so. You can easily search in Github repo or source code using part of log string. Translation would make this way more complicated. Also, if you are running something like bot, you should know english.

2021-11-09 21:11 UTC, Czechbol commented on unverify/database.py
> +        return result
> I think there was way to return number of affected rows. That would also handle that ValueError raising since you could just do delete and then return number of affected rows and check it.

That makes zero sense as I am deleting only one object.

2021-11-09 21:20 UTC, ArcasCZ commented on unverify/database.py
> +        return result
It makes sense since you don't have to raise ValueError, but you try to delete it and then you got 0 or 1 rows affected.

Then you can decide if you want to check for 1 (found and deleted) or 0 (none was found) and change user output, or just ignore it.

2021-11-09 21:24 UTC, Czechbol commented on unverify/database.py
> +    def get(guild_id) -> GuildConfig:
Correct

2021-11-09 21:39 UTC, Czechbol commented on unverify/database.py
> +        - :class:`sqlalchemy.orm.exc.MultipleResultsFound`: Multiple items were found (which is not expected).
I saw this as an option - listing the errors as bullet points but can be changed back

2021-11-09 21:39 UTC, Czechbol commented on unverify/database.py
> +                guild_id=member.guild.id,
correct

2021-11-09 21:39 UTC, Czechbol commented on unverify/database.py
> +        :class:`UnverifyItem`: The removed item.
I guess, it looked fine in my editor preview, tho

2021-11-09 21:39 UTC, Czechbol commented on unverify/database.py
> +            raise ValueError
> There are `ValueError` raised a lot, maybe they should have some content describing what is wrong? I can be convinced otherwise. In my modules, I've been using `return None` instead of raising exceptions, I wonder what is "prettier" solution.

Hmm, let's do it this way. If it's about finding stuff and not finding it, then `None` is alright. However if there is an ongoing unverify already or similar problem a `ValueError` would be the better option IMHO.

2021-11-09 21:39 UTC, Czechbol commented on unverify/database.py
> +        :class:`Optional[UnverifyItem]`
not replying on future occurences

2021-11-09 21:39 UTC, Czechbol commented on unverify/database.py
> +        return result
if you waited until I go through the whole review you would notice that I intend to change this.

2021-11-09 21:39 UTC, Czechbol commented on unverify/module.py
> +from discord import Guild, Member
I don't want it to take up horizontal space when type hinting. It makes the methods look worse than they are.

2021-11-09 21:39 UTC, Czechbol commented on unverify/module.py
> +from discord.ext import tasks, commands
Some of these could be reduced, but as I noted earlier, I am more okay with wordier imports than repeating the full name in type hinting. (That smells like Java and I don't support it)

2021-11-09 21:39 UTC, Czechbol commented on unverify/module.py
> +                        ),
> Also, if you are running something like bot, you should know english.

I don't agree. Not everyone is comfortable at using english. On the other way this whole repo is in english so IDK. To be discussed I guess.

2021-11-09 21:39 UTC, Czechbol commented on unverify/module.py
> +                        f"Returning role {role.name} to {member.name} ({member.id}) failed. Insufficient permissions.",
I have brain damage from writing all of this in two days

2021-11-09 21:39 UTC, Czechbol commented on unverify/module.py
> +    ) -> tuple[list[int], list[int]]:
huh? I am running Python 3.9.7, Dockerfile is on 3.10 and I did not encounter any issues. Are you sure?

2021-11-09 21:39 UTC, Czechbol commented on unverify/module.py
> +            await ctx.reply(_(ctx, "Is this member really unverified?"))
Does not matter how you say it, message stays the same.

2021-11-09 21:41 UTC, ArcasCZ commented on unverify/database.py
> +            raise ValueError
Still there's an option of returning rows affected. It should be faster.

2021-11-09 22:27 UTC, Czechbol commented
Comments should be resolved now

2021-11-11 19:32 UTC, sinus-x approved these changes
ACK

2021-11-12 23:30 UTC, merged