Rework Verify
pumpkin-py/pumpkin-management pull request #63
Opened 2022-10-13 20:01 UTC by ArcasCZ

![image](https://user-images.githubusercontent.com/6602975/195697758-a917ad91-4d0c-4a03-93f2-430d86bf394a.png)

This is schema of the new database

2022-10-14 14:44 UTC, ArcasCZ commented
- Add basic functions for DB objects.
 - Remove blocked parameter as it's not needed
 - Rename role_id to group_id because of smaller chances of typo / logical error

2022-10-16 22:30 UTC, ArcasCZ commented
Non-tested version.

 - fix imports
 - fix helper functions
 - fix verification commands
 - fix admin commands
 - remove data management functions

2022-10-17 10:25 UTC, ArcasCZ commented
- [ ] Mapping import
- [ ] Message editing
- [ ] Rule adding / removing
- [ ] Rule-Group relation adding removing
- [ ] Update whois
- [ ] Update rwhois
- [ ] Rework welcome-message command structure

2022-10-17 11:36 UTC, ArcasCZ commented
I've been using "group" to describe Discord roles, because of easy typo between role_id and rule_id. However this caused inconsistency in communication with users. So I'd rather sacrifice this typo protection for being consistent and call DC roles as roles.

2022-10-17 16:22 UTC, BorekZnovustvoritel requested changes

2022-10-17 16:22 UTC, BorekZnovustvoritel commented on verify/module.py
> +        if not ctx.message.attachments[0].filename.lower().endswith("json"):
`"json"` is not `csv` I am afraid.

2022-10-17 16:22 UTC, BorekZnovustvoritel commented on verify/module.py
> +            value=mapping.username + "@" + mapping.domain if mapping else "-",
Does `mapping.username` return `None` or `''` if not defined? This would throw errors if it was the first case.

2022-10-17 16:25 UTC, ArcasCZ commented on verify/database.py
> +            roles.append(VerifyRole(role_id=role, guild_id=self.guild_id))
Yep, fixed.

2022-10-17 16:26 UTC, ArcasCZ commented on verify/database.py
> +    def save(self):
We don't. Removed.

2022-10-17 16:29 UTC, ArcasCZ commented on verify/database.py
> +    def add(guild_id: int, username: str, domain: str, rule: VerifyRule):
But not every mapping has VerifyRule. Mappings without rule are considered as banned / blocked.

2022-10-17 16:29 UTC, ArcasCZ commented on verify/database.py
> +        guild_id: int, rule: VerifyRule = None, username: str = "", domain: str = ""
Same as above.

2022-10-17 16:31 UTC, ArcasCZ commented on verify/database.py
> +            username, at, domain = email.lower().rpartition("@")
Thanks, fixed.

2022-10-17 16:32 UTC, ArcasCZ commented on verify/database.py
> +        message = session.query(VerifyMessage).filter_by(
Thanks, renamed to db_message.

2022-10-17 16:34 UTC, ArcasCZ commented on verify/module.py
> +    async def verification_groupstrip(self, ctx, *members: Union[discord.Member, int]):
As far as I know the convention was that we want to have these things nested because of possible conflicts 🤔

2022-10-17 16:34 UTC, ArcasCZ commented on verify/module.py
> +    async def verification_grouprolestrip(self, ctx, role: discord.Role):
Same reply as above.

2022-10-17 16:40 UTC, ArcasCZ commented on verify/module.py
> +            value=mapping.username + "@" + mapping.domain if mapping else "-",
VerifyMapping.username and VerifyMapping.domain must not be None because they are part of primary key.

2022-10-17 16:41 UTC, ArcasCZ commented on verify/module.py
> +        if not ctx.message.attachments[0].filename.lower().endswith("json"):
Thanks for pointing out.

2022-10-17 18:49 UTC, ArcasCZ commented
Tested and ready for review.

2022-10-18 18:49 UTC, sinus-x requested changes

2022-10-18 18:49 UTC, sinus-x commented on verify/database.py
> +            List of VerifyRule
You are mixing Napoleon-style docstrings with Google-style ones. I'd prefer if it all was
```py
"""Get guild rules.

:param guild_id: Guild ID.
:param name: Optional search name.
:return: List of VerifyRules
"""
```

2022-10-18 18:49 UTC, sinus-x commented on verify/database.py
> +    def get(guild_id: int, name: str = None) -> List[VerifyRule]:
I know this is how this is how it is done in the documentation, but recently we've started using class methods instead. It works the same, but it is a bit cleaner.
```py
@classmethod
def get(cls, guild_id: int, name: Optional[str] = None) -> List[VerifyRule]:
    ...
```
...and this also applies to the rest of the functions. It is non-blocking comment, but I'd like to see it done if possible.

2022-10-18 18:49 UTC, sinus-x commented on whois/module.py
> +        dc_member = ctx.guild.get_member(db_member[0].user_id)
- If it returns a list, should it be `db_members`?
- Can it return multiple items? If so, why should be the first one be used?

2022-10-18 18:49 UTC, sinus-x commented on verify/module.py
> +        if not db_member or db_member[0].code is None:
Same as for Whois, why is it the first one? There should be at least a comment.

2022-10-18 18:49 UTC, sinus-x commented on verify/module.py
> +        db_member = db_member[0]
Reassigning to different object types is anti-pattern.

2022-10-18 18:49 UTC, sinus-x commented on verify/module.py
> +    async def verification_groupstrip(self, ctx, *members: Union[discord.Member, int]):
I'm ok with this.

2022-10-18 18:49 UTC, sinus-x commented on verify/module.py
> +    async def verification_message(self, ctx):
This subcommand should stay `welcome-message`.

2022-10-18 18:49 UTC, sinus-x commented on verify/module.py
> +            return
d.py 2.0 has [a conventor](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#discord-attachment) for this, we should try to use it.

2022-10-18 19:28 UTC, ArcasCZ commented on verify/database.py
> +            List of VerifyRule
My fault. Fixed.

2022-10-18 19:48 UTC, ArcasCZ commented on whois/module.py
> +        dc_member = ctx.guild.get_member(db_member[0].user_id)
Yes, it should be db_members.

In those cases it must list with length 0 or 1.

Fixed.

2022-10-18 20:01 UTC, ArcasCZ commented on verify/module.py
> +        db_member = db_member[0]
Fixed.

2022-10-18 20:04 UTC, ArcasCZ commented on verify/module.py
> +    async def verification_message(self, ctx):
Fixed.

2022-10-18 20:09 UTC, ArcasCZ commented on verify/module.py
> +    async def verification_groupstrip(self, ctx, *members: Union[discord.Member, int]):
@sinus-x OK with the change or do you want to have groupstrip as separate command? 🤔

2022-11-18 14:37 UTC, closed without merging